name: Teste

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  API-Tests-Postman-Collection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://Rapha3la.github.io/ron-bugado-academy12.2-api-postman/report.html

    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v4

      - name: Verificar Versões
        run: |
          newman --version
          node --version

      - name: Instalar Newman Reporter
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Executar Testes com Newman
        run: newman run ./ronbugado-collecition-ci.json -e ./ronbugado-environments-ci.json --reporters cli,htmlextra --reporter-htmlextra-export ./results/report.html

      - name: Salvar Relatório dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-test-report
          path: ./results/report.html

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer Upload dos Relatórios
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: ./results/

      - name: Publicar Relatórios
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: postman-test-report
